ALTER TABLE public.characters
  ADD COLUMN IF NOT EXISTS character_class TEXT,
  ADD COLUMN IF NOT EXISTS track TEXT,
  ADD COLUMN IF NOT EXISTS xp INTEGER NOT NULL DEFAULT 0;

ALTER TABLE public.characters
  ALTER COLUMN str_score SET DEFAULT 1,
  ALTER COLUMN dex_score SET DEFAULT 1,
  ALTER COLUMN int_score SET DEFAULT 1,
  ALTER COLUMN res_score SET DEFAULT 1,
  ALTER COLUMN cha_score SET DEFAULT 1,
  ALTER COLUMN per_score SET DEFAULT 0,
  ALTER COLUMN pa_current SET DEFAULT 12,
  ALTER COLUMN pa_max SET DEFAULT 12;